config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, presence: true
  validates :post, presence: true
  validates :text, presence: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_commit :increment_comments_count, on: :create

  private

  def increment_comments_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :author, presence: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_commit :increment_likes_count, on: :create

  private

  def increment_likes_count
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_create :increment_posts_count

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_posts_count
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment added successfully'
    else
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post: @post)
    @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to user_posts_path(current_user), notice: 'Post created successfully'
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::Passwords::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::Passwords::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::Passwords::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::Passwords::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::Passwords::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with(model: Comment.new, url: user_post_comments_path(@user, @post), method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :text, 'Comment' %>
    <%= form.text_area :text %>
  </div>

  <%= form.submit 'Add Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'function_link' %>
      <%= link_to 'Sign in', new_user_session_path, class: 'function_link' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<html>
  <head>
    <%= stylesheet_link_tag "styles" %>
  </head>

  <body>
    <div class='container'>
      <div class='user-card'>
        <%= render partial: 'shared/user_card', locals: { user: @user } %>
      </div>

      <% @user.posts.each do |post| %>
        <a href="<%= user_post_path(@user, post) %>">
          <div class='post-container'>
            <h2 class='post-title'><%= post.title %></h2>
            <p><%= truncate(post.text, length: 50, separator: ' ') %></p>
            <p class='counters'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
          </div>
          
          <% if post.recent_comments.present? %>
            <div class='comments-section'>
              <% post.recent_comments.includes([:author]).each do |comment| %>
                <p class='comment'><%= comment.author.name %>: <%= comment.text %></p>
              <% end %>
            </div>
          <% end %>
        </a>
      <% end %>

      <%= button_to 'Create Post', new_user_post_path(current_user), method: :get %>
    </div>
  </body>

app/views/posts/new.html.erb
<%= form_with(model: @post, url: user_posts_path(current_user), method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :title, 'Title' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text, 'Text' %>
    <%= form.text_area :text, class: 'form-control' %>
  </div>

  <%= form.submit 'Create Post', class: 'btn btn-primary' %>
<% end %>

app/views/posts/show.html.erb
<html>
  <head>
    <%= stylesheet_link_tag "styles" %>
  </head>

  <body>
    <%= form_with(model: @post.likes.new, local: true, url: user_post_likes_path(@user, @post)) do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <%= form.submit 'Like', class: 'like-button' %>
    <% end %>

    <div class='container'>
      <div class='post-container'>
        <p>This post was written by: <%=@post.author.name %></p>
        <h2 class='post-title'><%= @post.title %></h2>
        <p><%= @post.text %></p>
        <p class='counters'>Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
      </div>
      
      <% if @post.comments.present? %>
        <div class='comments-section'>
          <% @post.comments.includes([:author]).each do |comment| %>
            <p class='comment'><%= comment.author.name %>: <%= comment.text %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= link_to 'Add Comment', new_user_post_comment_path(@user, @post) %>
  </body>
</html>

app/views/shared/_user_card.html.erb
<ul class="photo-container">
  <li><img src="https://th.bing.com/th/id/R.df818c6db2fe74a4230ccc863663226e?rik=Bt%2fD%2bcd60%2bv0KQ&pid=ImgRaw&r=0" alt="<%= user.name %>'s Photo" /></li>
</ul>

<ul class="card-details">
  <li class="user-name"><%= user.name %></li>
  <li class="card-dets-num">Number of posts: <%= user.posts_counter %></li>
</ul>

app/views/users/index.html.erb
<!DOCTYPE html>

<html>
  <head>
    <%= stylesheet_link_tag "styles" %>
  </head>

  <body>
    <div class='container'>
      <h1>Users</h1>
      <% @users.each do |user| %>
        <a href="<%= user_path(user) %>" class="user-card">
          <%= render partial: 'shared/user_card', locals: { user: user } %>
        </a>
      <% end %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<html>
  <head>
    <%= stylesheet_link_tag "styles" %>
  </head>

  <body>
    <div class='container'>
      <div class='user-card'>
        <%= render partial: 'shared/user_card', locals: { user: @user } %>
      </div>

      <div class='bio'>
        <p><strong>Bio</strong></p>
        <p><%= @user.bio %></p>
      </div>

      <div>
        <% @user.recent_posts.each do |post| %>
          <a href="<%= user_post_path(@user, post) %>">
            <div class='post-container'>
              <h2 class='post-title'><%= post.title %></h2>
              <p><%= truncate(post.text, length: 50, separator: ' ') %></p>
              <p class='counters'>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
            </div>
          </a>
        <% end %>
      </div>

      <p class='see-posts'><a href="<%= user_posts_path(@user) %>">See all posts</a></p>
    </div>
  </body>
</html>